name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg

          token: ${{ secrets.METRICS_TOKEN }}

          user: umayanga-ithis

          template: classic

          base: header, activity, community, repositories, metadata

          config_timezone: Asia/Colombo

          plugin_languages: yes
          plugin_languages_limit: 8

          plugin_isocalendar: yes

          plugin_habits: yes

          plugin_followup: yes

          plugin_stars: yes

          plugin_traffic: yes

          plugin_lines: yes

          plugin_topics: yes

          plugin_repositories: yes

          plugin_achievements: yes
